### PR TITLE
Bugfix for grunt 1.0 / lodash 4.0 + 

### LINKED ISSUE #10: not working with grunt 1.0
pluck is removed in loadsh 4.0 and cause

Warning: grunt.util._.chain(...).pluck is not a function Used --force, continuing.

use map instead would just work fine.

### PR DESCRIPTION
**Pull request by amurf**
Pluck was removed in favour of map in lodash v4.0.0+ and this syntax
has been supported from at least 1.3 onwards.

This fixes #10 and is backwards compatible. 

See https://github.com/lodash/lodash/wiki/Changelog#v400

### CODE REVIEW

**Comment by rafecolton** [comment]
Confirmed this is both necessary and sufficient

**Comment by johnbburg** [comment]
Why not merge this?
