### ISSUE TITLE
not working with grunt 1.0

### ISSUE THREAD

**Issue by nickhsieh** [unbalanced/grunt-simple-watch#10]
pluck is removed in loadsh 4.0 and cause

Warning: grunt.util._.chain(...).pluck is not a function Used --force, continuing.

use map instead would just work fine.

**Comment by ve3** [comment]
I have the same problem.
